version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: noorfit-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: noorfit-server
    restart: always
    env_file:
      - ./server/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/noorfit
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: noorfit-client
    restart: always
    environment:
      - VITE_API_BASE_URL=http://10.16.38.220:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  mongo_data:
